packages:
  - apps/*
  - libs/*
catalog:
  "@biomejs/biome": 2.5.3
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - expo-dev-client@57.0.8
  - expo-dev-launcher@57.0.8
  - expo-dev-menu@57.0.8
