import type { TranslationResource } from './en';

/** Spanish bundle. Key-aligned with `en` (compiler-enforced). Copy pending native review (R6). */
export const es: TranslationResource = {
  translation: {
    general: {
      save: 'Guardar',
      saving: 'Guardando…',
    },
    brand: {
      name: 'AI Study Buddy',
    },
    error: {
      network: 'Error de red. Vuelve a intentarlo.',
    },
    nav: {
      myLessons: 'Mis lecciones',
      myPdfFiles: 'Mis archivos PDF',
      newLesson: 'Nueva lección',
      settings: 'Ajustes',
      openAccountMenu: 'Abrir menú de cuenta de {{label}}',
      lesson: 'Lección',
      study: 'Estudiar',
      results: 'Resultados',
      logIn: 'Iniciar sesión',
      signUp: 'Registrarse',
    },
    home: {
      savedLessons: 'Mis lecciones',
      openDemo: 'Abrir lección de ejemplo',
      loading: 'Cargando mis lecciones…',
      empty: 'Aún no tienes lecciones. Crea una para empezar.',
      error: 'No pudimos cargar tus lecciones.',
      retry: 'Intentar de nuevo',
      openLesson: 'Abrir {{title}}',
      createdDate: '{{date}}',
      delete: {
        action: 'Eliminar {{title}}',
        confirmHeadline: '¿Eliminar esta lección?',
        confirmBody: 'Esto elimina la lección y su progreso de forma permanente.',
        confirmAction: 'Eliminar',
        cancelAction: 'Cancelar',
        failed: 'No pudimos eliminar esa lección.',
      },
    },
    pdfList: {
      heading: 'Tus PDFs',
      loading: 'Cargando tus PDFs…',
      empty: 'Aún no hay PDFs extraídos. Sube uno para empezar.',
      error: 'No pudimos cargar tus PDFs.',
      retry: 'Intentar de nuevo',
      status: {
        ready: 'Listo para generar',
        failed: 'Generación fallida',
        generated: 'Lección lista',
      },
      action: {
        generate: 'Generar',
        retry: 'Reintentar',
        openLesson: 'Abrir lección',
        generateA11y: 'Generar {{filename}}',
        retryA11y: 'Reintentar {{filename}}',
        openLessonA11y: 'Abrir lección de {{filename}}',
      },
      createdDate: '{{date}}',
      pageCount: '{{count}} páginas',
      delete: {
        action: 'Eliminar {{filename}}',
        confirmHeadline: '¿Eliminar este PDF?',
        confirmBody: 'Esto elimina el PDF y sus datos extraídos de forma permanente.',
        confirmAction: 'Eliminar',
        cancelAction: 'Cancelar',
        failed: 'No pudimos eliminar ese PDF.',
      },
    },
    lessons: {
      count_one: '{{count}} lección',
      count_other: '{{count}} lecciones',
    },
    entitlements: {
      loading: 'Cargando tu perfil…',
      error: {
        message: 'No pudimos cargar tu perfil.',
        retry: 'Intentar de nuevo',
      },
    },
    fonts: {
      loading: 'Cargando fuentes…',
      error: {
        message:
          'Se produjo un error al cargar las fuentes. Por favor, intenta reiniciar la aplicación.',
      },
    },
    upload: {
      intro: 'Sube un PDF para generar una lección',
      apiKeyRequired: {
        message: 'Se requiere una clave de API para generar lecciones.',
        action: 'Agregar clave de API',
      },
      cannotCreate: 'No puedes crear lecciones. Contacta a soporte.',
      chooseFile: 'Elige un PDF',
      dialogHeadline: 'Subir PDF',
      dialogClose: 'Cerrar',
      loading: 'Extrayendo…',
      filenameLabel: 'Archivo',
      pageCountLabel: 'Páginas',
      imageCountLabel: 'Imágenes',
      continue: 'Continuar',
      // task-13/Slice-3 — native Spanish translations (replaces the Slice-2 verbatim-English stub).
      constraintsHint: 'Máximo {{maxMb}} MB, {{maxPages}} páginas',
      retryAction: 'Intentar de nuevo',
      imageCount_one: '{{count}} imagen extraída',
      imageCount_other: '{{count}} imágenes extraídas',
      error: {
        unsupportedType: 'Solo se admiten archivos PDF',
        fileTooLarge: 'Este archivo es demasiado grande (máx. 10 MB)',
        tooManyPages: 'Este PDF tiene demasiadas páginas (máx. 20)',
        scannedNotSupported: 'Este PDF parece escaneado; todavía no podemos leer su texto',
        corrupt: 'No se pudo abrir este PDF',
        extractionFailed: 'Ocurrió un error al leer tu PDF',
        unauthenticated: 'Inicia sesión para subir el archivo',
      },
    },
    generation: {
      dialogHeadline: 'Generar lección',
      provider: {
        heading: 'Proveedor de IA',
      },
      model: {
        heading: 'Modelo',
      },
      composition: {
        heading: 'Contenido de la lección',
        instructionalOnly: 'Solo instructivo',
        activityOnly: 'Solo actividades',
        both: 'Ambos',
      },
      generate: 'Generar lección',
      step: {
        reading: 'Leyendo contenido',
        generating: 'Generando diapositivas',
        attaching: 'Adjuntando imágenes',
        status: {
          done: 'listo',
          current: 'en curso',
          upcoming: 'próximo',
        },
      },
      ready: {
        slideCount_one: '{{count}} diapositiva generada',
        slideCount_other: '{{count}} diapositivas generadas',
        composition: 'Composición: {{composition}}',
        openInPlayer: 'Abrir en el reproductor',
      },
      error: {
        missingKey: 'Se requiere una clave de API para generar lecciones.',
        invalidKey: 'Tu clave de API fue rechazada. Revísala en Ajustes.',
        invalidModel:
          'Ese proveedor o modelo ya no está disponible. Elige otro e inténtalo de nuevo.',
        platformKeyUnavailable:
          'La generación de lecciones no está disponible temporalmente. Inténtalo de nuevo.',
        rateLimited: 'Alcanzaste el límite del proveedor. Vuelve a intentarlo en un momento.',
        timeout: 'La generación tardó demasiado. Vuelve a intentarlo.',
        generationFailed: 'Algo salió mal al generar tu lección. Vuelve a intentarlo.',
        documentNotReady: 'Este documento aún no está listo. Vuelve a subir tu PDF.',
        unauthenticated: 'Inicia sesión para generar una lección.',
        persistFailed: 'No se pudo guardar tu lección. Vuelve a intentarlo.',
        providerDisabled:
          'Ese proveedor está deshabilitado actualmente. Elige otro e inténtalo de nuevo.',
        action: {
          retry: 'Volver a intentar',
          settings: 'Ir a Ajustes',
          signIn: 'Iniciar sesión',
        },
      },
    },
    aiModel: {
      groq: {
        gptOss20b: 'GPT-OSS 20B',
        gptOss120b: 'GPT-OSS 120B',
        qwen36_27b: 'Qwen 3.6 27B',
      },
      openai: {
        gpt56Luna: 'GPT-5.6 Luna',
        gpt56Terra: 'GPT-5.6 Terra',
      },
      anthropic: {
        claudeHaiku45: 'Claude Haiku 4.5',
        claudeSonnet5: 'Claude Sonnet 5',
      },
      google: {
        gemini36Flash: 'Gemini 3.6 Flash',
        gemini25Flash: 'Gemini 2.5 Flash',
      },
      xai: {
        grok43: 'Grok 4.3',
        grok45: 'Grok 4.5',
      },
      deepseek: {
        v4Flash: 'DeepSeek V4 Flash',
        v4Pro: 'DeepSeek V4 Pro',
      },
    },
    lesson: {
      title: 'Lección {{id}}',
      start: 'Empezar a estudiar',
      viewResults: 'Ver resultados',
    },
    player: {
      loading: 'Cargando lección…',
      next: 'Siguiente',
      back: 'Atrás',
      slideOf: 'Diapositiva {{current}} de {{total}}',
      empty: {
        message: 'Esta lección aún no tiene diapositivas.',
      },
      error: {
        message: 'No se pudo cargar esta lección.',
        retry: 'Reintentar',
      },
      slideImage: {
        expand: 'Ver imagen a pantalla completa',
        close: 'Cerrar imagen',
        dialog: 'Visor de imágenes',
      },
      slideBody: {
        scroll: 'Contenido de la diapositiva',
      },
    },
    results: {
      score: '{{correct}} / {{total}}',
      scorePercent: '{{percent}}%',
      scoreAnnouncement: '{{score}}, {{percent}}',
      retake: 'Repetir actividades',
      backHome: 'Volver a mis lecciones',
      completeHeadline: 'Lección completada',
      completeBody: 'Has llegado al final de esta lección.',
      saveFailed: 'No se pudo guardar este intento',
      retrySave: 'Intentar de nuevo',
    },
    auth: {
      email: 'Correo electrónico',
      password: 'Contraseña',
      submit: 'Iniciar sesión',
      signingIn: 'Iniciando sesión…',
      signingOut: 'Cerrando sesión…',
      toSignUp: '¿No tienes cuenta? Regístrate',
      toLogIn: '¿Ya tienes cuenta? Inicia sesión',
      logOut: 'Cerrar sesión',
      logOutError: 'Ocurrió un error al cerrar sesión.',
      logOutRetry: 'Intentar de nuevo',
      logOutConfirmHeadline: '¿Cerrar sesión?',
      logOutConfirmBody: 'Tendrás que iniciar sesión de nuevo para acceder a tus lecciones.',
      logOutConfirmAction: 'Cerrar sesión',
      logOutCancelAction: 'Cancelar',
      error: {
        email: 'Introduce un correo electrónico válido',
        invalidCredentials: 'Correo electrónico o contraseña incorrectos',
      },
    },
    settings: {
      title: 'Ajustes',
      language: {
        heading: 'Idioma',
        a11yLabel: 'Elige un idioma',
      },
      apiKey: {
        inputLabel: 'Clave de API',
        loadingStatus: 'Verificando el estado de tu clave de API…',
        showSettings: 'Mostrar configuración de claves de API',
        screenTitle: 'Configuración de claves de API',
        replace: 'Reemplazar',
        remove: 'Eliminar',
        savedStatus: 'Clave de {{provider}} guardada · Actualizada {{date}}',
        provider: {
          groq: 'Groq',
          openai: 'OpenAI',
          anthropic: 'Anthropic',
          google: 'Google',
          xai: 'xAI',
          deepseek: 'DeepSeek',
        },
        guidanceTemplate: '¿No tienes una clave? Consíguela en {{provider}}',
        guidance: '¿No tienes una clave? Consíguela en Groq',
        removeConfirmHeadline: '¿Eliminar clave de API?',
        removeConfirmBody: 'Deberás agregar una nueva clave para volver a generar lecciones.',
        removeConfirmAction: 'Confirmar eliminación',
        removeConfirmCancelAction: 'Cancelar',
        manager: {
          addHeading: 'Agregar proveedor',
          addNew: 'Agregar nuevo proveedor',
          selectProvider: 'Seleccionar proveedor',
          emptyMessage: 'No hay claves de API guardadas',
          disabled: 'Deshabilitado',
        },
        error: {
          empty: 'Ingresa tu clave de API.',
          providerDisabled:
            'Este proveedor está deshabilitado actualmente y no puede recibir una nueva clave.',
        },
      },
    },
    activity: {
      mcq: {
        submit: 'Enviar',
        correct: 'Correcto',
        incorrect: 'Incorrecto',
        explanation: 'Explicación',
        unavailable: 'Esta pregunta no está disponible',
      },
      matching: {
        submit: 'Enviar',
        correct: '¡Todo correcto!',
        incorrect: 'No del todo',
        correctPair: 'correcto',
        incorrectPair: 'incorrecto',
        explanationHeading: 'Por qué',
        summary: '{{correct}} de {{total}} correctos',
        unavailable: 'Esta actividad no está disponible',
      },
      fillInTheBlank: {
        submit: 'Enviar',
        correct: '¡Correcto!',
        incorrect: 'Incorrecto',
        explanationHeading: 'Por qué',
        unavailable: 'Esta actividad no está disponible',
        blankInput: 'Completa el espacio',
      },
      openEnded: {
        submit: 'Enviar',
        yourAnswer: 'Tu respuesta',
        modelAnswer: 'Respuesta modelo',
        explanationHeading: 'Por qué',
        unavailable: 'Esta actividad no está disponible',
        answerInput: 'Tu respuesta',
      },
      flashcard: {
        reveal: 'Mostrar respuesta',
        recalled: 'Recordado',
        notRecalled: 'No recordado',
        recalledConfirmed: 'Marcado como recordado',
        notRecalledConfirmed: 'Marcado como no recordado',
        answerHeading: 'Respuesta',
        explanationHeading: 'Por qué',
        unavailable: 'Esta actividad no está disponible',
      },
    },
  },
};
