import type { TranslationResource } from './en';

/** Portuguese bundle. Key-aligned with `en` (compiler-enforced). Copy pending native review (R6). */
export const pt: TranslationResource = {
  translation: {
    general: {
      save: 'Salvar',
      saving: 'Salvando…',
      cancel: 'Cancelar',
      delete: 'Excluir',
      close: 'Fechar',
      disabled: 'Desabilitado',
      confirm: 'Confirmar',
      errorMessage: 'Ocorreu um erro inesperado',
      errorRetry: 'Tentar novamente',
    },
    brand: {
      name: 'AI Study Buddy',
    },
    error: {
      network: 'Erro de rede. Tente novamente.',
    },
    nav: {
      myLessons: 'Minhas lições',
      myPdfFiles: 'Meus arquivos PDF',
      newLesson: 'Nova lição',
      settings: 'Configurações',
      openAccountMenu: 'Abrir menu da conta de {{label}}',
      lesson: 'Lição',
      study: 'Estudar',
      results: 'Resultados',
      logIn: 'Entrar',
      signUp: 'Cadastrar',
    },
    home: {
      savedLessons: 'Minhas lições',
      openDemo: 'Abrir lição de demonstração',
      loading: 'Carregando minhas lições…',
      empty: 'Você ainda não tem lições. Crie uma para começar.',
      error: 'Não foi possível carregar suas lições.',
      retry: 'Tentar de novo',
      openLesson: 'Abrir {{title}}',
      createdDate: '{{date}}',
      delete: {
        action: 'Excluir {{title}}',
        confirmHeadline: 'Excluir esta lição?',
        confirmBody: 'Isso remove permanentemente a lição e o progresso.',
        confirmAction: 'Excluir',
        cancelAction: 'Cancelar',
        failed: 'Não foi possível excluir essa lição.',
      },
    },
    pdfList: {
      heading: 'Seus PDFs',
      loading: 'Carregando seus PDFs…',
      empty: 'Ainda não há PDFs extraídos. Envie um para começar.',
      error: 'Não foi possível carregar seus PDFs.',
      retry: 'Tentar de novo',
      status: {
        ready: 'Pronto para gerar',
        failed: 'Geração falhou',
        generated: 'Lição pronta',
      },
      action: {
        generate: 'Gerar',
        retry: 'Tentar novamente',
        openLesson: 'Abrir lição',
        generateA11y: 'Gerar {{filename}}',
        retryA11y: 'Tentar novamente {{filename}}',
        openLessonA11y: 'Abrir lição de {{filename}}',
      },
      createdDate: '{{date}}',
      pageCount: '{{count}} páginas',
      delete: {
        action: 'Excluir {{filename}}',
        confirmHeadline: 'Excluir este PDF?',
        confirmBody: 'Isso remove permanentemente o PDF e seus dados extraídos.',
        confirmAction: 'Excluir',
        cancelAction: 'Cancelar',
        failed: 'Não foi possível excluir esse PDF.',
      },
    },
    lessons: {
      count_one: '{{count}} lição',
      count_other: '{{count}} lições',
    },
    entitlements: {
      loading: 'Carregando seu perfil…',
      error: {
        message: 'Não foi possível carregar seu perfil.',
        retry: 'Tentar novamente',
      },
    },
    fonts: {
      loading: 'Carregando fontes…',
      error: {
        message: 'Ocorreu um erro ao carregar as fontes. Por favor, tente reiniciar a aplicação.',
      },
    },
    upload: {
      intro: 'Envie um PDF para gerar uma lição',
      apiKeyRequired: {
        message: 'É necessária uma chave de API para gerar lições.',
        action: 'Adicionar chave de API',
      },
      cannotCreate: 'Você não pode criar lições. Entre em contato com o suporte.',
      chooseFile: 'Escolha um PDF',
      dialogHeadline: 'Enviar PDF',
      dialogClose: 'Fechar',
      loading: 'Extraindo…',
      filenameLabel: 'Arquivo',
      pageCountLabel: 'Páginas',
      imageCountLabel: 'Imagens',
      continue: 'Continuar',
      // task-13/Slice-3 — native Portuguese translations (replaces the Slice-2 verbatim-English stub).
      constraintsHint: 'Máx. {{maxMb}} MB, {{maxPages}} páginas',
      retryAction: 'Tentar novamente',
      imageCount_one: '{{count}} imagem extraída',
      imageCount_other: '{{count}} imagens extraídas',
      error: {
        unsupportedType: 'Apenas arquivos PDF são aceitos',
        fileTooLarge: 'Este arquivo é muito grande (máx. 10 MB)',
        tooManyPages: 'Este PDF tem muitas páginas (máx. 20)',
        scannedNotSupported: 'Este PDF parece digitalizado; ainda não conseguimos ler o texto',
        corrupt: 'Não foi possível abrir este PDF',
        extractionFailed: 'Algo deu errado ao ler seu PDF',
        unauthenticated: 'Faça login para enviar o arquivo',
      },
    },
    generation: {
      dialogHeadline: 'Gerar lição',
      provider: {
        heading: 'Provedor de IA',
      },
      model: {
        heading: 'Modelo',
      },
      composition: {
        heading: 'Conteúdo da lição',
        instructionalOnly: 'Somente instrutivo',
        activityOnly: 'Somente atividades',
        both: 'Ambos',
      },
      generate: 'Gerar lição',
      step: {
        reading: 'Lendo conteúdo',
        generating: 'Gerando slides',
        attaching: 'Anexando imagens',
        status: {
          done: 'concluído',
          current: 'em andamento',
          upcoming: 'próximo',
        },
      },
      ready: {
        slideCount_one: '{{count}} slide gerado',
        slideCount_other: '{{count}} slides gerados',
        composition: 'Composição: {{composition}}',
        openInPlayer: 'Abrir no player',
      },
      error: {
        missingKey: 'É necessária uma chave de API para gerar lições.',
        invalidKey: 'Sua chave de API foi rejeitada. Verifique-a em Configurações.',
        invalidModel:
          'Esse provedor ou modelo não está mais disponível. Escolha outro e tente novamente.',
        platformKeyUnavailable:
          'A geração de lições está temporariamente indisponível. Tente novamente.',
        rateLimited: 'Você atingiu o limite do provedor. Tente novamente em instantes.',
        timeout: 'A geração demorou demais. Tente novamente.',
        generationFailed: 'Algo deu errado ao gerar sua lição. Tente novamente.',
        documentNotReady: 'Este documento ainda não está pronto. Reenvie seu PDF.',
        unauthenticated: 'Entre na sua conta para gerar uma lição.',
        persistFailed: 'Não foi possível salvar sua lição. Tente novamente.',
        providerDisabled:
          'Esse provedor está desativado no momento. Escolha outro e tente novamente.',
        action: {
          retry: 'Tentar novamente',
          settings: 'Ir para Configurações',
          signIn: 'Entrar',
        },
      },
    },
    lesson: {
      title: 'Lição {{id}}',
      start: 'Começar a estudar',
      viewResults: 'Ver resultados',
    },
    player: {
      loading: 'Carregando lição…',
      next: 'Próximo',
      back: 'Voltar',
      slideOf: 'Slide {{current}} de {{total}}',
      progress: {
        lesson: 'Lição {{n}}',
        activity: 'Atividade {{n}}',
      },
      empty: {
        message: 'Esta lição ainda não tem slides.',
      },
      error: {
        message: 'Não foi possível carregar esta lição.',
        retry: 'Tentar novamente',
      },
      slideImage: {
        expand: 'Ver imagem em tela cheia',
        close: 'Fechar imagem',
        dialog: 'Visualizador de imagens',
      },
      slideBody: {
        scroll: 'Conteúdo do slide',
      },
    },
    results: {
      score: '{{correct}} / {{total}}',
      scorePercent: '{{percent}}%',
      scoreAnnouncement: '{{score}}, {{percent}}',
      retake: 'Refazer atividades',
      backHome: 'Voltar às minhas lições',
      completeHeadline: 'Lição concluída',
      completeBody: 'Você chegou ao final desta lição.',
      saveFailed: 'Não foi possível salvar esta tentativa',
      retrySave: 'Tentar novamente',
    },
    auth: {
      email: 'E-mail',
      password: 'Senha',
      submit: 'Entrar',
      signingIn: 'Entrando…',
      signingOut: 'Saindo…',
      toSignUp: 'Não tem conta? Cadastre-se',
      toLogIn: 'Já tem conta? Entre',
      logOut: 'Sair',
      logOutError: 'Ocorreu um erro ao sair.',
      logOutRetry: 'Tentar novamente',
      logOutConfirmHeadline: 'Sair da conta?',
      logOutConfirmBody: 'Você precisará entrar novamente para acessar suas lições.',
      logOutConfirmAction: 'Sair',
      logOutCancelAction: 'Cancelar',
      error: {
        email: 'Informe um e-mail válido',
        invalidCredentials: 'E-mail ou senha inválidos',
      },
    },
    settings: {
      title: 'Configurações',
      language: {
        heading: 'Idioma',
        a11yLabel: 'Escolha um idioma',
      },
      apiKey: {
        inputLabel: 'Chave de API',
        loadingStatus: 'Verificando o status da sua chave de API…',
        showSettings: 'Mostrar configurações de chaves de API',
        screenTitle: 'Configurações de chaves de API',
        replace: 'Substituir',
        remove: 'Remover',
        savedStatus: 'Chave da {{provider}} salva. Atualizada em {{date}}.',
        guidanceTemplate: 'Não tem uma chave? Obtenha uma na {{provider}}',
        guidance: 'Não tem uma chave? Obtenha uma na Groq',
        removeConfirmHeadline: 'Remover chave de API?',
        removeConfirmBody:
          'Tem certeza que deseja remover esta chave? \nVocê precisará adicionar uma nova chave para gerar lições novamente.',
        removeConfirmAction: 'Confirmar remoção',
        removeConfirmCancelAction: 'Cancelar',
        manager: {
          addHeading: 'Adicionar provedor',
          addNew: 'Adicionar novo provedor',
          selectProvider: 'Selecionar provedor',
          emptyMessage: 'Nenhuma chave de API salva',
        },
        error: {
          empty: 'Informe sua chave de API.',
          providerDisabled:
            'Este provedor está desativado no momento e não pode receber uma nova chave.',
        },
      },
    },
    activity: {
      mcq: {
        submit: 'Enviar',
        correct: 'Correto',
        incorrect: 'Incorreto',
        explanation: 'Explicação',
        unavailable: 'Esta pergunta não está disponível',
      },
      matching: {
        submit: 'Enviar',
        correct: 'Tudo correto!',
        incorrect: 'Quase',
        correctPair: 'correto',
        incorrectPair: 'incorreto',
        explanationHeading: 'Por quê',
        summary: '{{correct}} de {{total}} corretos',
        unavailable: 'Esta atividade não está disponível',
      },
      fillInTheBlank: {
        submit: 'Enviar',
        correct: 'Correto!',
        incorrect: 'Incorreto',
        explanationHeading: 'Por quê',
        unavailable: 'Esta atividade não está disponível',
        blankInput: 'Preencha o espaço',
      },
      openEnded: {
        submit: 'Enviar',
        yourAnswer: 'Sua resposta',
        modelAnswer: 'Resposta modelo',
        explanationHeading: 'Por quê',
        unavailable: 'Esta atividade não está disponível',
        answerInput: 'Sua resposta',
      },
      flashcard: {
        reveal: 'Mostrar resposta',
        recalled: 'Lembrei',
        notRecalled: 'Não lembrei',
        recalledConfirmed: 'Marcado como lembrado',
        notRecalledConfirmed: 'Marcado como não lembrado',
        answerHeading: 'Resposta',
        explanationHeading: 'Por quê',
        unavailable: 'Esta atividade não está disponível',
      },
    },
  },
};
