-- multi-provider-ai-keys (Slice 1, task-1) — composite-PK migration.
--
-- Promotes user_ai_keys from a single user_id PK (one key total per user) to a composite
-- PK (user_id, provider) so each user can hold one key per provider (≤1 key per provider,
-- up to 6 providers). A DB CHECK restricts `provider` to the closed six-value allow-list;
-- the three SECURITY DEFINER service_role-only RPCs are redefined to be per-provider.
--
-- Same Vault-vs-pgcrypto fallback caveat as the original migration: if hosted Vault is
-- unavailable, swap vault.create_secret/update_secret/decrypted_secrets for pgcrypto/pgsodium
-- bytea — the table shape and all higher layers are unaffected either way (risks.md R-enc).
--
-- Reversibility note (down migration not auto-generated by the CLI): to revert, run:
--   drop function if exists public.save_api_key(uuid, text, text);
--   drop function if exists public.remove_api_key(uuid, text);
--   drop function if exists public.get_api_key(uuid, text);
--   alter table public.user_ai_keys drop constraint if exists user_ai_keys_pkey;
--   alter table public.user_ai_keys drop constraint if exists user_ai_keys_provider_check;
--   alter table public.user_ai_keys add constraint user_ai_keys_pkey primary key (user_id);
-- (Old single-provider RPC definitions must be re-created manually from the original migrations.)

-- Drop old single-parameter RPCs before redefining with updated signatures.
drop function if exists public.save_api_key(uuid, text, text);
drop function if exists public.remove_api_key(uuid);
drop function if exists public.get_api_key(uuid);

-- Promote the PK from (user_id) to (user_id, provider) so each user holds ≤1 key per provider.
alter table public.user_ai_keys drop constraint user_ai_keys_pkey;
alter table public.user_ai_keys
  add constraint user_ai_keys_pkey primary key (user_id, provider);

-- Closed six-provider CHECK — server-side defense in depth; the client-side TS union and the
-- Edge Function's isAiProvider guard are the first line of defence, this is the DB backstop.
alter table public.user_ai_keys
  add constraint user_ai_keys_provider_check check (provider in ('groq','openai','anthropic','google','xai','deepseek'));

-- The select-own RLS policy (user_ai_keys_select_own) is unchanged from the original
-- migration — it already scopes to the owning user via auth.uid() = user_id and
-- works unchanged for the multi-row composite-PK table (all rows with the caller's
-- user_id remain readable; insert/update/delete remain restricted to service_role via
-- the Edge Functions). No policy change is needed here.

-- save_api_key(): upserts one provider's key, naming the Vault secret per (user, provider).
-- security definer + service_role-only execute: same model as the original (see original
-- migration header for the full rationale).
create function public.save_api_key(p_user_id uuid, p_provider text, p_api_key text)
returns table (provider text, updated_at timestamptz)
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_secret_id uuid;
  v_existing_secret_id uuid;
begin
  select uak.secret_id into v_existing_secret_id
  from public.user_ai_keys uak
  where uak.user_id = p_user_id
    and uak.provider = p_provider;

  if v_existing_secret_id is not null then
    perform vault.update_secret(v_existing_secret_id, p_api_key);
    v_secret_id := v_existing_secret_id;
  else
    -- Per-provider secret name: user_ai_key_<uid>_<provider> (spec.md Open decision, task-1).
    v_secret_id := vault.create_secret(
      p_api_key,
      'user_ai_key_' || p_user_id::text || '_' || p_provider
    );
  end if;

  insert into public.user_ai_keys as uak (user_id, secret_id, provider, updated_at)
  values (p_user_id, v_secret_id, p_provider, now())
  on conflict (user_id, provider) do update
    set secret_id  = excluded.secret_id,
        updated_at = now();

  return query
    select uak.provider, uak.updated_at
    from public.user_ai_keys uak
    where uak.user_id = p_user_id
      and uak.provider = p_provider;
end;
$$;

revoke all on function public.save_api_key(uuid, text, text) from public;
grant execute on function public.save_api_key(uuid, text, text) to service_role;

-- remove_api_key(): deletes only the named provider's row + its Vault secret.
create function public.remove_api_key(p_user_id uuid, p_provider text)
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_secret_id uuid;
begin
  select uak.secret_id into v_secret_id
  from public.user_ai_keys uak
  where uak.user_id = p_user_id
    and uak.provider = p_provider;

  if v_secret_id is not null then
    delete from vault.secrets where id = v_secret_id;
  end if;

  delete from public.user_ai_keys
  where user_id = p_user_id
    and provider = p_provider;
end;
$$;

revoke all on function public.remove_api_key(uuid, text) from public;
grant execute on function public.remove_api_key(uuid, text) to service_role;

-- get_api_key(): returns the decrypted key for one specific provider (generate-lesson Edge only).
create function public.get_api_key(p_user_id uuid, p_provider text)
returns table (provider text, api_key text)
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
begin
  return query
    select uak.provider, vs.decrypted_secret
    from public.user_ai_keys uak
    join vault.decrypted_secrets vs on vs.id = uak.secret_id
    where uak.user_id = p_user_id
      and uak.provider = p_provider;
end;
$$;

revoke all on function public.get_api_key(uuid, text) from public;
grant execute on function public.get_api_key(uuid, text) to service_role;
