-- ai-key-management (Slice 1, task-1) -- encrypted AI-provider key store.
--
-- Encryption mechanism: Supabase Vault (spec.md Open decision 1, default path). The
-- pre-Slice-1 spike confirmed `supabase_vault` is installed and functional on the local
-- dev stack (docker exec supabase_db_<project> psql -> `vault.create_secret` / the
-- `vault.decrypted_secrets` view round-tripped a test secret). Hosted-project availability
-- was NOT independently confirmed by a human at the gate; if it turns out unavailable there,
-- swap this migration's Vault calls for the documented pgcrypto/pgsodium bytea fallback --
-- the `user_ai_keys` table shape and every higher layer (ApiKeyStatus, DAO, service, hook,
-- UI) are unaffected either way (risks.md R-enc).
--
-- Reversibility note (down migration is not auto-generated by the CLI): to revert, run
--   drop function if exists public.save_api_key(uuid, text, text);
--   drop table if exists public.user_ai_keys;
-- (Vault secrets created via the function are left in vault.secrets -- delete manually by id.)

create extension if not exists supabase_vault with schema vault;
create extension if not exists pgcrypto;

-- Non-secret metadata only -- no key material lives in this table (task-1 Goal).
create table public.user_ai_keys (
  user_id uuid primary key references auth.users (id) on delete cascade,
  secret_id uuid not null,
  provider text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.user_ai_keys is
  'Per-user AI provider key metadata. secret_id is an opaque reference into vault.secrets -- '
  'never the key itself. All writes go through the manage-api-key Edge Function''s service '
  'role via save_api_key() (remove_api_key() lands in Slice 2/task-9); the client''s only '
  'direct access is the RLS-scoped select below.';

alter table public.user_ai_keys enable row level security;

-- Select-only for the owning user. No insert/update/delete grant to authenticated/anon --
-- all writes happen through the service-role Edge Function, which bypasses RLS.
create policy "user_ai_keys_select_own" on public.user_ai_keys
  for select
  to authenticated
  using (auth.uid() = user_id);

grant select on public.user_ai_keys to authenticated;
-- Edge manage-api-key lists keys via the service-role admin client after save/remove.
grant select on public.user_ai_keys to service_role;

-- save_api_key(): the only way the Vault secret + metadata row are written. security definer
-- so it can reach the vault schema (not directly grantable to authenticated); execute is
-- restricted to service_role, so an authenticated client cannot call this even with a valid
-- JWT (it can only reach it indirectly via the Edge Function, which authenticates the caller
-- and supplies p_user_id itself -- never a client-supplied id).
create function public.save_api_key(p_user_id uuid, p_provider text, p_api_key text)
returns table (provider text, updated_at timestamptz)
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_secret_id uuid;
  v_existing_secret_id uuid;
begin
  select uak.secret_id into v_existing_secret_id
  from public.user_ai_keys uak
  where uak.user_id = p_user_id;

  if v_existing_secret_id is not null then
    perform vault.update_secret(v_existing_secret_id, p_api_key);
    v_secret_id := v_existing_secret_id;
  else
    v_secret_id := vault.create_secret(p_api_key, 'user_ai_key_' || p_user_id::text);
  end if;

  insert into public.user_ai_keys as uak (user_id, secret_id, provider, updated_at)
  values (p_user_id, v_secret_id, p_provider, now())
  on conflict (user_id) do update
    set secret_id = excluded.secret_id,
        provider = excluded.provider,
        updated_at = now();

  return query
    select uak.provider, uak.updated_at from public.user_ai_keys uak where uak.user_id = p_user_id;
end;
$$;

revoke all on function public.save_api_key(uuid, text, text) from public;
grant execute on function public.save_api_key(uuid, text, text) to service_role;
