-- ai-provider-registry-backend (Slice 1, task-2) — user_ai_keys.provider FK swap.
--
-- Replaces the closed six-value CHECK on user_ai_keys.provider (added in
-- 20260722000000_multi_provider_ai_keys.sql) with a real foreign key to the new
-- public.ai_providers catalog (task-1), so integrity is enforced against live catalog rows
-- rather than a hardcoded allow-list baked into a past migration (@s8). ON DELETE RESTRICT
-- (the default) blocks deleting a provider that still has saved keys (@s9) — disabling a
-- provider (ai_providers.enabled = false) remains the only supported way to retire it while
-- learner keys exist for it.
--
-- Ordering is load-bearing: this migration's timestamp must sort after task-1's, since the FK
-- validation needs the seeded ai_providers rows to already exist. Verified safe: the CHECK being
-- replaced already restricts `provider` to exactly the six ids task-1 seeds, so no existing
-- user_ai_keys row can violate the new FK.
--
-- Reversibility note (down migration not auto-generated by the CLI): to revert, run:
--   alter table public.user_ai_keys drop constraint if exists user_ai_keys_provider_fkey;
--   alter table public.user_ai_keys
--     add constraint user_ai_keys_provider_check
--     check (provider in ('groq','openai','anthropic','google','xai','deepseek'));

alter table public.user_ai_keys drop constraint user_ai_keys_provider_check;

alter table public.user_ai_keys
  add constraint user_ai_keys_provider_fkey
  foreign key (provider) references public.ai_providers (id);
