-- ai-provider-registry-backend (Slice 1, task-1) — provider/model catalog tables.
--
-- Moves provider/model metadata out of hand-mirrored TypeScript (models.ts,
-- libs/types/src/ai-provider.ts) into two Postgres tables so a provider can be renamed,
-- re-modelled, reordered or retired via Supabase Studio with no code deploy (@s1). Seeded to
-- today's exact six providers/thirteen models (@s5) so shipping this migration is a behavioural
-- no-op until an operator edits a row.
--
-- WARNING: `groq` is also the hardcoded platform-generation provider (PLATFORM_TEXT_MODEL_ID).
-- Disabling `groq` here disables platform (non-BYOK) generation entirely (task-7/D14) — there is
-- no separate platform-provider flag.
--
-- Reversibility note (down migration not auto-generated by the CLI): to revert, run:
--   drop table if exists public.ai_provider_models;
--   drop table if exists public.ai_providers;
-- (Must run before task-2's migration is reverted, since task-2 adds a FK to ai_providers.)

create table public.ai_providers (
  id text primary key,
  name text not null,
  guidance_url text,
  enabled boolean not null default true,
  sort_order integer not null
);

alter table public.ai_providers enable row level security;

create policy "ai_providers_select_authenticated" on public.ai_providers
  for select
  to authenticated
  using (true);

revoke all on public.ai_providers from anon, authenticated;
grant select on public.ai_providers to authenticated;
grant all on public.ai_providers to service_role;

create table public.ai_provider_models (
  provider_id text not null references public.ai_providers (id) on delete cascade,
  model_id text not null,
  label text not null,
  vision boolean not null default false,
  is_vision_default boolean not null default false,
  sort_order integer not null,
  primary key (provider_id, model_id),
  -- A vision-default model must itself be vision-capable (@s3).
  check (not is_vision_default or vision)
);

-- At most one vision-default model per provider (@s2) — a partial unique index rather than a
-- boolean-pair CHECK, since the uniqueness spans rows, not columns within one row.
create unique index ai_provider_models_one_vision_default_per_provider
  on public.ai_provider_models (provider_id)
  where is_vision_default;

alter table public.ai_provider_models enable row level security;

create policy "ai_provider_models_select_authenticated" on public.ai_provider_models
  for select
  to authenticated
  using (true);

revoke all on public.ai_provider_models from anon, authenticated;
grant select on public.ai_provider_models to authenticated;
grant all on public.ai_provider_models to service_role;

-- Seed — today's exact catalog (@s5), `sort_order` fixing the canonical picker order
-- (groq, openai, anthropic, google, xai, deepseek) that `select` has no inherent order for.
insert into public.ai_providers (id, name, guidance_url, enabled, sort_order)
values
  ('groq', 'Groq', 'https://console.groq.com/keys', true, 1),
  ('openai', 'OpenAI', 'https://platform.openai.com/api-keys', true, 2),
  ('anthropic', 'Anthropic', 'https://console.anthropic.com/settings/keys', true, 3),
  ('google', 'Google', 'https://aistudio.google.com/app/apikey', true, 4),
  ('xai', 'xAI', 'https://console.x.ai', true, 5),
  ('deepseek', 'DeepSeek', 'https://platform.deepseek.com/api_keys', true, 6);

insert into public.ai_provider_models
  (provider_id, model_id, label, vision, is_vision_default, sort_order)
values
  ('groq', 'openai/gpt-oss-20b', 'GPT-OSS 20B', false, false, 1),
  ('groq', 'openai/gpt-oss-120b', 'GPT-OSS 120B', false, false, 2),
  ('groq', 'qwen/qwen3.6-27b', 'Qwen 3.6 27B', true, true, 3),
  ('openai', 'gpt-5.6-luna', 'GPT-5.6 Luna', true, true, 1),
  ('openai', 'gpt-5.6-terra', 'GPT-5.6 Terra', true, false, 2),
  ('anthropic', 'claude-haiku-4-5', 'Claude Haiku 4.5', true, true, 1),
  ('anthropic', 'claude-sonnet-5', 'Claude Sonnet 5', true, false, 2),
  ('google', 'gemini-3.6-flash', 'Gemini 3.6 Flash', true, true, 1),
  ('google', 'gemini-2.5-flash', 'Gemini 2.5 Flash', true, false, 2),
  ('xai', 'grok-4.3', 'Grok 4.3', true, true, 1),
  ('xai', 'grok-4.5', 'Grok 4.5', true, false, 2),
  ('deepseek', 'deepseek-v4-flash', 'DeepSeek V4 Flash', true, true, 1),
  ('deepseek', 'deepseek-v4-pro', 'DeepSeek V4 Pro', true, false, 2);
